export const termsContent = {
  lastUpdated: "April 1, 2022",
  sections: [
    {
      title: "Acceptance of the Terms of Service",
      content: `These Terms of Service are entered into by and between you and luxlaundryservice ("luxlaundryservice.com," "we," or "us"). The following terms and conditions, together with any documents they expressly incorporate by reference (collectively, the "Terms"), govern your access to and use of the luxlaundryservice.com website (and related domains) including all text, content, photographs, images, audio, graphics, and any software (which includes any files or images incorporated in or generated by the software) available on such website (collectively referred to herein as the "Website"), including luxlaundryservice.com's weekly and/or on-demand laundry services offered on or through such Website (the "Services"), and our related mobile applications (the "Applications"), whether as a guest or a registered user. The Website, Services, and Applications are collectively referred to herein as the "luxlaundryservice.com Platform."

Please read the Terms carefully before you start to use the luxlaundryservice.com Platform. By using any part of the luxlaundryservice.com Platform or by clicking to accept or agree to the Terms when this option is made available to you, you accept and agree to be bound and abide by these Terms and our Privacy Policy, found at https://www.luxlaundryservice.com/privacy/, and incorporated herein by reference. If you do not want to agree to these Terms or the Privacy Policy, you must not access or use the luxlaundryservice.com Platform.

The Services are offered and made available to users who are 18 years of age or older and who reside in the United States. By using the Services, you represent and warrant that you are of legal age to form a binding contract with luxlaundryservice.com and that you meet all of the foregoing eligibility requirements. If you do not meet all of these requirements, you may not access or use the Services.`
    },
    {
      title: "Changes to the Terms of Service",
      content: `We may revise and update these Terms from time to time in our sole discretion. All changes are effective immediately when we post them, and apply to all access to and use of the luxlaundryservice.com Platform thereafter. Your continued use of the luxlaundryservice.com Platform following the posting of revised Terms means that you accept and agree to the changes. You are expected to check this page from time to time so you are aware of any changes, as they are binding on you.`
    },
    {
      title: "The Services",
      content: `You can schedule Services via the Website and/or Applications. After scheduling Services using the Website and/or Application, luxlaundryservice.com or a third party, which is an independent contractor working with luxlaundryservice.com, will provide the Services.`
    },
    {
      title: "Ownership, Licenses, and Limitations",
      content: `Proprietary Rights. The luxlaundryservice.com Platform is owned and operated by luxlaundryservice.com.

As between the parties, luxlaundryservice.com owns all right, title, and interest, including but not limited to all intellectual property and proprietary rights, in and to the luxlaundryservice.com Platform. The luxlaundryservice.com Platform is protected by copyright, trademark, domain name, trade dress, domain name, patent, trade secret, international treaties and/or other intellectual property and proprietary rights and laws of the United States and other countries. Except as otherwise indicated in the luxlaundryservice.com Platform and except for the trademarks, service marks and trade names of other companies that are or may be displayed in the luxlaundryservice.com Platform, all trademarks, service marks and trade names are owned by luxlaundryservice.com.`
    },
    {
      title: "User Requirements and Conduct",
      content: `In order to use most aspects of the luxlaundryservice.com Platform, you must register for and maintain an active personal user account (an "Account"). Account registration requires you to submit to luxlaundryservice.com certain personal information, such as your name, address, and mobile phone number, as well as at least one valid credit card (to be processed by a third party payment processor). You agree to maintain accurate, complete, and up-to-date information in your Account, review the fees to be charged for your use of the Services ("Fees"); and authorize luxlaundryservice.com to charge your credit card for any and all Fees incurred by you for your use of the Services.

The Service is not available for use by persons under the age of 18. You may not authorize third parties to use your Account, and you may not allow persons under the age of 18 to use the Services unless they are supervised by you.`
    },
    {
      title: "User Representations",
      content: `You represent and warrant to luxlaundryservice.com that you will:
(a) maintain the security of your user identification, password, and other confidential information relating to your Account
(b) maintain the security, confidentiality, and integrity of all messages and content
(c) pay for all Fees resulting from the use of your Account
(d) comply with these Terms
(e) comply with all applicable U.S. and international laws, statutes, ordinances, rules, regulations, contracts and applicable licenses`
    },
    {
      title: "Promotional Offers",
      content: `luxlaundryservice.com may, in our sole discretion, create promotional codes that may be redeemed for Service credit or other features or benefits. You agree that promotional codes:
(i) may only be used for the intended audience and purpose
(ii) may not be duplicated, sold, or transferred
(iii) may not be used to exceed quantity limits
All promotional codes may be disabled at any time and are not valid for cash.`
    },
    {
      title: "Damaged Items",
      content: `luxlaundryservice.com follows the standards and policies set forth by the Fabricare Industry and the International Fabricare Institute. We exercise utmost care in cleaning and processing garments entrusted to us and use such processes, which, in our opinion, are best suited to the nature and conditions of each individual garment. Nevertheless, we cannot assume responsibility for inherent weaknesses or defects in materials which may result in tears or development of small holes in fabric that are not readily apparent prior to processing.

Please report any damaged items from your order to hello@luxlaundryservice.com within 24 hours of delivery. luxlaundryservice.com is not responsible for any damaged items reported after this time.

luxlaundryservice.com's liability with respect to any damaged items shall not exceed ten (10) times our charge for cleaning that garment, regardless of brand or condition. Notwithstanding the foregoing, luxlaundryservice.com will not be responsible for any reparation beyond $200.00.`
    },
    {
      title: "Lost Items",
      content: `Please report any missing items from your order to hello@luxlaundryservice.com within 24 hours of delivery. luxlaundryservice.com is not responsible for any missing items reported after this time. luxlaundryservice.com will not be responsible for any lost item beyond $200.00, even if the order costs over $200.00 to process. Any single lost item will not be valued beyond $25.00, even if the fair market value for the item is more.`
    },
    {
      title: "Pick-Up and Delivery",
      content: `Our goal is to provide convenient and frictionless Services to our customers and are willing to leave completed orders wherever the customer dictates. However, luxlaundryservice.com is not responsible for any missing or damaged items if the order is not personally received by you and picked up and delivered by an luxlaundryservice.com employee.`
    },
    {
      title: "Missed Pickup",
      content: `Lux Laundry has incorporated email pickup tool in its software to help you remember your laundry pickup day. However, if you do forget to leave your laundry out, we will charge a missed pickup fee ($35) to cover the cost of a driver going to your home or business.

To Avoid Missed Pickup Fees: Please cancel the pickup on your account by 4 am ET the day of your scheduled pickup. Any cancellations after 4am ET are subject to Missed Pickup fees.`
    },
    {
      title: "Excessive Amounts of Debris",
      content: `In order to maintain a high level of cleanliness and efficiency, we request that you ensure your laundry is free from excessive amounts of debris. This includes but is not limited to dirt, sand, soil, pet hair, food particles, and other similar substances. If your laundry contains an excessive amount of debris, which may hinder the proper cleaning process, an additional fee of $50 will be charged.`
    },
    {
      title: "Payment Terms",
      content: `Payment Methods: We accept various payment methods including credit cards, debit cards, and other forms of electronic payment.

Insufficient Funds Fee: Every declined card transaction due to insufficient funds will incur a $5 fee for each failed transaction. This fee will be charged to your account immediately upon notification of the failed transaction.

Responsibility: It is your responsibility to ensure that sufficient funds are available in your account to cover your transactions. Lux Laundry is not responsible for any overdraft or other bank fees incurred as a result of insufficient funds.`
    },
    {
      title: "WARRANTY DISCLAIMER",
      content: `THE luxlaundryservice.com PLATFORM IS PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, luxlaundryservice.com AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS AND REPRESENTATIVES DISCLAIM WITH RESPECT TO THE luxlaundryservice.com PLATFORM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE.`
    },
    {
      title: "LIMITATION OF LIABILITY",
      content: `TO THE FULLEST EXTENT PROVIDED BY LAW AND EXCEPT AS PROVIDED IN SECTION 5.G (DAMAGED ITEMS) ABOVE, IN NO EVENT WILL luxlaundryservice.com, ITS AFFILIATES, OR THEIR LICENSORS, SERVICE PROVIDERS, EMPLOYEES, AGENTS, OFFICERS, OR DIRECTORS BE LIABLE FOR DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE, OR INABILITY TO USE, THE luxlaundryservice.com PLATFORM.`
    },
    {
      title: "Governing Law",
      content: `These terms of use shall be governed by and construed in accordance with the laws of the State of Delaware. Any disputes arising out of or relating to these terms shall be subject to the exclusive jurisdiction of the courts in the State of Delaware.`
    },
    {
      title: "Contact Information",
      content: `If you have any questions about these terms of use, please contact us at 484-246-9163 or email us at hello@luxlaundryservice.com.`
    }
  ]
}; 